### ISSUE TITLE
Updated 1 Existing Custom Formats: ["DV HDR10"] Keeps Repeating

### ISSUE THREAD

**Issue by 5stringdeath** [recyclarr/recyclarr#109]
Running recyclarr says all CF's are updated, but this single CF will remain - updated but stuck.

v2.4.0 (Branch.tags-v2.4.0.Sha.54d980e14cb3339ba7733ab4a21eaabd3f4fd1e9)

[Logs](https://gist.github.com/5stringdeath/2dba714ef9a1212206761446363af7ba#file-trash_2022-08-26_12-36-06-log)

These are the CF's in the yaml in question:

custom_formats:
      # A list of custom formats to sync to Radarr. Must match the "trash_id" in the guide JSON.
      - trash_ids:
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (720/1080p)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - e23edd2482476e595fb990b12e7c609c # DV HDR10
          - 58d6a88f13e2db7f5059c41047876f00 # DV
          - 55d53828b9d81cbe20b02efd00aa0efd # DV HLG
          - a3e19f8f627608af0211acd02bf89735 # DV SDR
          - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
          - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
          - e61e28db95d22bedcadf030b8f156d96 # HDR
          - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
          - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ
          - 9364dd386c9b4a1100dde8264690add7 # HLG

**Comment by rcdailey** [comment]
Thanks for the bug report!

The reason for this is `trash_regex`, which was added to CFs in the guides recently. Recyclarr has an algorithm that determines when custom formats are different between Radarr and the guide CFs. Because Radarr doesn't know about `trash_regex`, the comparison always shows a difference, and thus it always gets updated in Radarr when you run Recyclarr.

Good news is, this doesn't break anything. It just results in unnecessary API calls to Radarr. I'll have this fixed shortly. The fix I'm going with for this will be a little more scalable. From now on, any properties in guide CFs that begin with `trash_` are automatically stripped out and will not interfere with comparisons.
