### ISSUE TITLE
Don't exit one if PUID or PGID are defined

### ISSUE THREAD

**Issue by Ornias1993** [recyclarr/recyclarr#115]
Some projects, like TrueCharts, set PUID and PGID by default because it's easier that way.

Currently your project is the only one on the whole internet, that i'm aware of, that decided to completely nuke execution when these variables are defined. So that's definately a bad practice.

Please stick to a warning and don't `exit 1` when PUID or PGID is present.

**Comment by rcdailey** [comment]
Previously, the container used to start with a root user. I modeled the permissions scheme after LSIO containers. Now the container is rootless and `PUID`/`PGID` are no longer used. However, this is a breaking change, and I needed a way to make sure users are aware that a change is needed, even if they don't read the release notes.

A warning is not sufficient as that is very likely to go unnoticed, especially for folks that use automation but do not frequently monitor it. Exiting when these variables are defined was the best way I could think of at the time to spread awareness of the issue without causing mixed permission problems in the `/config` volume.

All this is to say: No, I won't remove this logic. At least, not yet. After some time, it won't be needed anymore and I'll remove it then. But for now it's going to stay. Quite frankly, there's a ton of different environments containers can run in and I can't change my software for every unique case. I could just as easily make the argument that TrueCharts (which I have zero experience with) should not be defining unwanted environment variables. There should be a way to turn them off on your side, which would allow the container execution to continue. You need to find a way to unset the environment variables.

I may be the only container "on the whole internet" that does this, but it's for good reason. You're only calling it "bad practice" because it's an inconvenience for you in your specific instance. It's actually a documented bad practice to have rootful containers that rely on these variables, and probably even worse to promote it by having an environment that automatically defines these env vars for "convenience". You're the only one that has an issue with it so far. Please find a way in TrueCharts to resolve your issue for now and keep an eye on the release notes in the future for when it gets removed.

**Comment by Ornias1993** [comment]
"It's actually a documented bad practice to have rootful containers that rely on these variables"

We know, we're actually one of the fiercest projects against using PUID and PGID and actually: PGID is deployed by us in a way that syncs it with kubernetes security policies, in such a way to give users somewhat of the same experience between securityContext and PGID.

We don't run things in root if we can help it and we're always extremely happy when projects move to docker/kubernetes native rootless deployment.

`exit 1` (aka: failed execution due to error) for something that objectively is `warn` not `err` level configuration mistakes, is a bad practice. Even worse is doing so without applying semver (which is basically the go-to standard for versioning besides calver).


---

Anyway: Your attitude towards people trying to help you distribute your work is rather rude, uncalled for and basically puts your minor project on the backburner for me.

**Comment by onedr0p** [comment]
> Anyway: Your attitude towards people trying to help you distribute your work is rather rude, uncalled for and basically puts your minor project on the backburner for me.

@Ornias1993 That is funny coming from your mouth. You have the worse attitude period which is why you are banned in so many places.

Anyways, your concerns with this project doesn't seem like an issue here, why is truenas scale or whatever passing env vars that don't need to exist in the container in the first place?

**Comment by Ornias1993** [comment]
> @Ornias1993 That is funny coming from your mouth. You have the worse attitude and the worse communication skills period which is why you are banned in so many online places.

I'm banned in precisely 2 places i'm aware of.... 

> Anyways, your concerns with this project doesn't seem like an issue here, why is truenas scale or whatever passing env vars that don't need to exist in the container in the first place? This is an non-issue, or an issue with truenas.

While I agree that we should setup that code on our side cleaner (which we where actually working on besides this issue), that does not mean non-failing things should be made failing.
(basically two wrongs to not make a right)

**Comment by rcdailey** [comment]
> we're actually one of the fiercest projects against using PUID and PGID

Yet you inherently set these for users without a way to disable them? Okay lol.

> Anyway: Your attitude towards people trying to help you distribute your work is rather rude, uncalled for and basically puts your minor project on the backburner for me.

I want to be perfectly clear about something. This project was started by me, *for* me. I decided to publicize my work for folks that would appreciate it. I don't really care about how popular or unpopular my project is, especially to you. I find it ironic that you criticize *my* attitude when your very first post already had a passive-aggressive tone with a lot of self-entitlement. I'm sorry, but I don't work for you.

I think this issue has run its course and I'm going to go ahead and lock it. I already have very little time to work on Recyclarr, I don't want to spend it arguing with irrational, self-entitled folks.

My very first reply contains all the information you need. Up to you how you want to work around this.
