### ISSUE TITLE
Ability to override rename inclusion setting for a CF

### ISSUE THREAD

**Issue by owine** [recyclarr/recyclarr#127]
Similar to having the ability to override a score, it would be nice to be able to override the rename inclusion setting when syncing a CF.

**Comment by rcdailey** [comment]
What is the "rename inclusion setting"?

**Comment by owine** [comment]
> What is the "rename inclusion setting"?

`includeCustomFormatWhenRenaming`

**Comment by rcdailey** [comment]
That's what I was thinking, but I wanted to be sure.

Exactly what is the value in having this? Honestly, I do not expect this to be something that changes often, if ever. Furthermore, this setting isn't in the JSON data in the guide, so it's still something you'd be manually setting (except you'd be doing it in YAML instead of clicking a simple checkbox).

Can you explain why you want this in Recyclarr, and how it is beneficial?
