### ISSUE TITLE
Allow defining non-Trash CFs

### ISSUE THREAD

**Issue by grapexy** [recyclarr/recyclarr#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I use a couple of my own CFs for personal LQ groups, prioritizing WEBDLs over WEBRips and other things. I got used to recyclarr yamls being the declarative source of truth for all my CFs and scores and it's very easy to forget those manually added to *arrs.

Could we add support for _custom_ custom formats? I imagine something like a path in yaml that contains CF jsons structured the same way as trash repo and with their own uuids. i.e:

```
├── personal_cfs
│   ├── radarr
│   │   └── cf
│   │       └── personal_cf.json
│   └── sonarr
│       └── cf
│           └── personal_cf.json

```

And yaml:
```
sonarr:
  - personal_custom_formats_dir: personal_cfs/sonarr/cf
```

**Comment by rcdailey** [comment]
You can already do this today:

1. Fork the official Trash git repository on Github.
1. Add, commit, and push your custom CFs in the usual paths (e.g. `docs/json/radarr/cf`).
   - Optionally, if you want to use your own paths for better separation from the official ones, you can put them anywhere you'd like. Just make sure you add that path to the existing list of paths under the relevant setting in `metadata.json` at the root of the trash repo, so that Recyclarr can find it).
1. Modify [your `settings.json`](https://recyclarr.dev/wiki/reference/settings-reference) to specify the URL to your fork of the Trash repo. Optionally specify a branch as well, otherwise it will use `master` on your fork.
