### ISSUE TITLE
Option to pull from Sonarr V3 release profiles

### ISSUE THREAD

**Issue by apathy** [recyclarr/recyclarr#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I've noticed when running a preview for a sonarr sync it was pulling from the Sonarr V4 release profiles: https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/#web-tier-01 (tier 02 and 03 as well) instead of https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/#p2p-groups-repackproper-release-profile for Sonarr V3, would really appreciate a way to pull from the guide made for V3.

**Comment by rcdailey** [comment]
Sonarr v4 does not have release profiles. It has custom formats.

The preview option will show you what you're syncing. So if you're using Sonarr v3 + release profiles, you'll see release profiles. If you're using Sonarr v4 + custom formats, then you'll see custom formats.

You need to use the right version of Sonarr depending on if you want to sync release profiles or custom formats.

In the future, please use the discussions tab at the top for questions, or if you feel there is a defect, use the Bug issue template instead of requesting a feature.

**Comment by apathy** [comment]
> Sonarr v4 does not have release profiles. It has custom formats.
> 
> The preview option will show you what you're syncing. So if you're using Sonarr v3 + release profiles, you'll see release profiles. If you're using Sonarr v4 + custom formats, then you'll see custom formats.
> 
> You need to use the right version of Sonarr depending on if you want to sync release profiles or custom formats.
> 
> In the future, please use the discussions tab at the top for questions, or if you feel there is a defect, use the Bug issue template instead of requesting a feature.

My apologies. I'll reply here since I've already opened this, but it does seem to be pulling from the custom formats section and while it does add to release profiles on Sonarr V3 the scores/groups etc are clearly from the V4 custom formats as you can see here:
![image](https://user-images.githubusercontent.com/12659760/216782898-8af348fa-7955-49fc-b574-4efe340bf24a.png)

**Comment by rcdailey** [comment]
I'm sorry, but there's nothing I can do without logs and other information that the bug template requests users submit. If you'd like me to look into this further, please resubmit as a bug and follow the template.
