### ISSUE TITLE
Add support to run init scripts during container initialization

### ISSUE THREAD

**Issue by paya-cz** [recyclarr/recyclarr#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

[linuxserver.io images support running custom init scripts located in /custom-cont-init.d/ folder](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/s6-overlay/s6-rc.d/init-custom-files/run). These scripts run as root and it is very useful to perform any runtime initialization during container startup. For example, I use it to modify container route table to route traffic via another container (VPN).

Currently, I don't see a feature like this in `recyclarr`, so the only workaround is to override `ENTRYPOINT` in custom `Dockerfile`, do the init in my own entrypoint, then delegate back to the original entrypoint via shell script. However, [`recyclarr` expects to run as user 1000](https://github.com/recyclarr/recyclarr/blob/master/docker/Dockerfile), so this is not a straightforward change. Additionally, after I change the `ENTRYPOINT`, I now have to check every single `recyclarr` image update and verify whether the original entrypoint has been changed in the update or not, and update my startup shell script accordingly to invoke the correct original entrypoint.

**Comment by rcdailey** [comment]
The official recyclarr image is rootless by design. `1000:1000` is the default UID:GID but can be changed with the `user:` property in compose.

I will not be adding this functionality because it requires significant overhaul of the way the image is set up and requires root which is no longer recommended for docker containers for security reasons. There's nothing about Recyclarr itself that requires root privileges. Thus, making the container itself requires root is unnecessarily prohibitive, especially in environments where containers are running on nodes that should or may not have root privileges.

I recommend you work on your own `linuxserver/recyclarr` image if you want this functionality. Or, if possible, find an approach that allows you to properly network traffic in the way you want without requiring modification to application containers.
