### ISSUE TITLE
Add support for sending sync success pings to health monitor services

### ISSUE THREAD

**Issue by BallistiX09** [recyclarr/recyclarr#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There's not any easy way currently to know when something has gone wrong during syncing when Recyclarr is running in cron mode, without manually checking in every so often.

It would be ideal if there was an option to send success success pings (or failures if preferred) to something like healthchecks.io or any similar sites, which would give an obvious warning that something needs fixed.

**Comment by rcdailey** [comment]
Hey thanks for the report. Could you give some examples of the kinds of failures you've observed that would call for this?

Something potentially useful to you is the notifications work I'm doing (#114). I plan to set this up so that every `sync` performed results in a "report" sent via notification, which will indicate success or failure.

Normally health checks are for "running services". In this case, Recyclarr itself isn't continuously running, so it might not be a good fit. But notifications might be what you're looking for.

Let me know.

**Comment by BallistiX09** [comment]
Ahhh yeah, that's exactly what I was looking for! Sorry, I'd searched a bunch of keywords for that but notifications wasn't one of them I guess!

The healthchecks.io site I mentioned works exaclty like that, generating a URL which can be hit whenever a process is completed, only giving a notification if that process doesn't check in after an expected delay. So that notifications support would be ideal when it's finished off!

**Comment by rcdailey** [comment]
Thanks for getting back with me so quickly. If it's all the same to you, I'll go ahead and mark this one as a duplicate. I'll be sure to give healthchecks.io a look as well to see if I can incorporate anything from there.
