### ISSUE TITLE
Allow config yaml to dictate what is updated

### ISSUE THREAD

**Issue by snoopy82481** [recyclarr/recyclarr#43]
Feature Request:  
Allow config yaml to dictate what is updated

Detail:
Currently you have to specify sonarr or radarr in the CLI for the application to process that portion of the config file.  You have to run the command twice to update both sonarr and radarr to update both applications.  This makes a cron job have to run two separate times to update both sonarr and radarr.

Proposed Change:
Make the sonarr/radarr switch optional and have the config yaml run the options provided. But when sonarr/radarr is supplied it will work as it currently does.

**Comment by rcdailey** [comment]
This has been on my mind for a while. I really do want to clean up the command line interface. Thank you for the report!

**Comment by rcdailey** [comment]
For backward compatibility, I was thinking of leaving `trash sonarr` and `trash radarr`. Plus there might also be cases where users still want to run one but not the other without modifying their config files.

What I'd do here is add a new `all` subcommand (e.g. `trash all`) or allow `trash` (without a subcommand) to do that. What do you think?

**Comment by snoopy82481** [comment]
I was thinking instead of making sonarr/radarr subcommands mandatory they would be an optional subcommand.  I like the `trash` option much better but you still have to supply the `-c|--config`.  That way if you don't want to change any cronjob/scheduled task you won't have to, or if you have an automated trigger for trash updates to only one or the other of the arrs.

I hope that's coming across clear.  My head says it does, but sometimes it doesn't come across right on the screen.

**Comment by rcdailey** [comment]
Sounds like (maybe) we're saying the same thing? I always feel like examples speak louder than words, so let me try this:

- `./trash sonarr`: Runs only Sonarr parts of `trash.yml`
- `./trash radarr`: Runs only Radarr parts of `trash.yml`
- `./trash` Runs both Sonarr and Radarr parts of `trash.yml`
- `./trash -c myconfig.yml` Runs both Sonarr and Radarr parts of `myconfig.yml`

Does this map to what you were thinking?

**Comment by snoopy82481** [comment]
It does map to what I was thinking.  The 3rd option wasn't on my thoughts though.

**Comment by rcdailey** [comment]
`-c` would apply to all variations. Importantly, though, is that it is optional and without it, it will always use `-c trash.yml` as a default.

**Comment by snoopy82481** [comment]
Sounds good to me.

**Comment by skayo** [comment]
I think doing a potentially destructive operation without specifying any parameters is a bad behaviour. Most CLIs I know just show a help message when run without any arguments/flags, like `jq` or `heroku`. This concept also described [here](https://clig.dev/#help).

So I'd rather suggest something like this:
```properties
trash sync:radarr    # Sync radarr
trash sync:sonarr    # Sync sonarr
trash sync           # Sync all
```

**Comment by nipuna-perera** [comment]
I agree.

**Comment by rcdailey** [comment]
I'm personally leaning towards `all` as well. I don't like `all` because "What does 'all' mean out of context?". So I probably need to think about it some more. But that will most likely be the direction I go.

For those of you that request this feature, is there a reason you want `trash all` over something like `trash sonarr && trash radarr`? What are the benefits?

**Comment by rcdailey** [comment]
I probably won't use that `command:subcommand` syntax because it's unusual. I think the more "defacto" standard would be `./trash sync --radarr` and `./trash sync --sonarr`. Which I think looks nice. But then again, both `radarr` and `sonarr` do not/will not always have the same set of options. For example, 2.0 will introduce these options:

```txt
./trash sonarr --list-release-profiles
./trash sonarr --list-terms 123abc
```

These two options are sonarr-specific. It wouldn't make sense to do `./trash sync --radarr --list-release-profiles`, and it's difficult to guard against this while still maintaining a good user experience.

Another approach might be:

```sh
./trash sync # sync all
./trash sync radarr # sync only radarr; same as './trash radarr'
./trash sync sonarr # sync only sonarr; same as './trash sonarr'
```

The downside here is a more over-engineered implementation (nested subcommands do not give me warm & fuzzy feelings inside).

I think you are on the right track with the word "sync". It is probably the most appropriate command verb I can think of for what this tool is doing. Thanks for the inspiration!

**Comment by skayo** [comment]
I actually named the binary `trash-sync` on my computer, because I already have a `trash` binary due to [trash-cli](https://github.com/sindresorhus/trash-cli). So I just do `trash-sync sonarr` and `trash-sync radarr`. Not sure if you're gonna rename the binary tho...



> I probably won't use that `command:subcommand` syntax because it's unusual.

It's the syntax that the Heroku CLI uses, which is widely regarded as a good example for an CLI.

**Comment by skayo** [comment]
Oh, `recyclarr` is a great name!

**Comment by rcdailey** [comment]
Yea, because I "recycle" (sync) the "trash"... Kind of cringe, but it's the best "arr" name I could come up with lol.
