### ISSUE TITLE
Quality profile name not valid

### ISSUE THREAD

**Issue by Palle34** [recyclarr/recyclarr#96]
I get this error althoug in radarr the profile is named exactly the same (2160p_TRaSH). 

`[WRN] The following quality profile names are not valid and should either be removed or renamed in your YAML config
[WRN] ["2160p_TRaSH"]`

**Comment by rcdailey** [comment]
@Palle34 what was the solution to the problem? Just in case others come across this in the future.

**Comment by Palle34** [comment]
There was no real problem..
It was simply my stupidity, as I used a port from another Radar instance ;D

**Comment by l3uddz** [comment]
Im seeing this on the latest version of Sonarr 4.0.0.344. Nothing has changed besides an update to Sonarr. Looks like recyclarr removed the custom formats associated with the quality profiles.

@rcdailey any tips to resolve this?

**Comment by l3uddz** [comment]
My issue was resolved by removing all existing custom formats and having recyclarr resync them. Not sure why this happened post upgrade but just an FYI for others if they come across this.

**Comment by rcdailey** [comment]
@l3uddz you should have opened a new issue instead of posting on an existing one. The whole point of the issue template is to gather the necessary information from you to allow me to answer your question.

If you still have your old cache and logs around, please open a new issue and I'm happy to look.
